"""
Autoregressive text generation using a pretrained language model.
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


def greedy_decode(model, tokenizer, prompt, max_new_tokens=20):
    """
    Generate text autoregressively using explicit greedy decoding.

    Input
    -----
    model : PreTrainedModel
        Pretrained causal language model.
    tokenizer : PreTrainedTokenizer
        Tokenizer associated with the model.
    prompt : str
        Initial text used as context for generation.
    max_new_tokens : int
        Maximum number of tokens to generate.

    Output
    ------
    generated_text : str
        Text obtained after autoregressive generation.
    """
    inputs = tokenizer(prompt, return_tensors="pt")
    input_ids = inputs["input_ids"].to(model.device)
    attention_mask = inputs["attention_mask"].to(model.device)

    for _ in range(max_new_tokens):
        with torch.no_grad():
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
            )

        logits = outputs.logits[:, -1, :]
        probabilities = torch.softmax(logits, dim=-1)
        next_token_id = torch.argmax(
            probabilities,
            dim=-1,
            keepdim=True,
        )

        input_ids = torch.cat(
            [input_ids, next_token_id],
            dim=-1,
        )

        attention_mask = torch.cat(
            [
                attention_mask,
                torch.ones(
                    (attention_mask.shape[0], 1),
                    dtype=attention_mask.dtype,
                    device=model.device,
                ),
            ],
            dim=-1,
        )

        if (
            tokenizer.eos_token_id is not None
            and next_token_id.item() == tokenizer.eos_token_id
        ):
            break

    generated_text = tokenizer.decode(
        input_ids[0],
        skip_special_tokens=True,
    )

    return generated_text


def standard_generate(model, tokenizer, prompt, max_new_tokens=20):
    """
    Generate text using the standard Transformers generation interface.

    Input
    -----
    model : PreTrainedModel
        Pretrained causal language model.
    tokenizer : PreTrainedTokenizer
        Tokenizer associated with the model.
    prompt : str
        Initial text used as context for generation.
    max_new_tokens : int
        Maximum number of tokens to generate.

    Output
    ------
    generated_text : str
        Text generated by the model.
    """
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
        )

    generated_text = tokenizer.decode(
        output_ids[0],
        skip_special_tokens=True,
    )

    return generated_text


if __name__ == "__main__":
    model_name = "HuggingFaceTB/SmolLM-135M"

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name)

    device = torch.device(
        "cuda" if torch.cuda.is_available() else "cpu"
    )
    model = model.to(device)
    model.eval()

    prompt = "Machine learning is"

    explicit_text = greedy_decode(
        model,
        tokenizer,
        prompt,
        max_new_tokens=20,
    )

    standard_text = standard_generate(
        model,
        tokenizer,
        prompt,
        max_new_tokens=20,
    )

    print("Explicit greedy decoding:")
    print(explicit_text)

    print("\nTransformers generate():")
    print(standard_text)