project:
  type: book
  output-dir: docs

book:
  title: "Data Science Across Domains"
  subtitle: "From Methods and Models to Business Applications"
  author: "Rodrigo Kang"
  language: en
  cover-image: cover.png

  sidebar:
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/rodrigokang/portfolio
      - icon: linkedin
        href: https://www.linkedin.com/in/rodrigojuankang/
      - icon: envelope
        href: "mailto:rodrigokang88@gmail.com"

  chapters:
    - index.qmd
    - preface.qmd
    - about.qmd
    - reading-guide.qmd
    - project-1.qmd
    - project-2.qmd
    - references.qmd

bibliography: references.bib
csl: ieee.csl

format:
  html:
    theme: cosmo
    code-copy: true
    code-line-numbers: true
    mermaid:
      theme: default
  pdf:
    include-in-header: header.tex
    latex-engine: xelatex
    documentclass: book
    fontsize: 12pt
    toc: true
    toc-depth: 4
    number-sections: true
    mainfont: "Linux Libertine O"
    link-citations: true
    mermaid:
      theme: default